### PR TITLE
[update] shell module

### PR DESCRIPTION
**Pull request by imthaghost**
Shell module is a center hub for all modules that allows user to be emersed into a shell by creating a CLI dashboard.

- Test by running the command `python3 main shell`
- Once in the shell test the commands `help` , `modules` 
- You can also check to see if the checkinModule works with the shell by typing `checkin`

### CODE REVIEW

**Comment by TasfiaAddrita** [comment]
Can you double-check what's up with colorama? 

image

**Comment by TasfiaAddrita** [comment]
Can you check what's up with `colorama`? 

image

**Comment by tempor1s** [comment]
Don’t think this really requires a version bump either. We could just keep it in develop until we add more features.

**Comment by tempor1s** [comment]
We’re any other modules added since last master merge? Would like to add them to the Homebrew Formula before merging.

@TasfiaAddrita Did you run ‘pipenv install’ after pulling?

**Comment by imthaghost** [comment]
> Can you check what's up with `colorama`?
> 
> image

`NameErrors` show up when a function isn't defined. Colorama not being defined means it wasn't imported properly. Did you pull the updated code or do `pipenv install`, colorama has always been a module in the application. I removed the catch block to see if that's what was bugging it. I also removed some redundancy with colorama so maybe thats why you got that error. But make sure you run `pipenv shell` and `pipenv install` If it still persists I'll have Bean look at it. 


Screen Shot 2019-12-29 at 2 31 56 AM


Appears to be working fine here.

**Comment by imthaghost** [comment]
> We’re any other modules added since last master merge? Would like to add them to the Homebrew Formula before merging.


No new modules were installed so no need to worry about the homebrew formulas. The shell is using only 3 external packages: `emoji`, `PyInquirer`, and `colorama`. Colorama has been in our application from the start so theres no need to worry about that module. As for the other 2 I used PyInquirer when I created the system wide credential functions just so you wouldn't have to worry about me installing it at some later date. I think the only one you need to double check is `emoji`. Its a module for well....emojis lmao. I convert unicode to emojis in the shell. 

```
welcome_emoji_list = ['\U0001F918',
                              '\U0001F44B', '\U0001F5A4', '\U0001F47D', '\U0001F642', '\U0001F601', '\U0001F603', '\U0001F435', '\U0001F40D',
                              '\U0001F996']
```

**Comment by TasfiaAddrita** [comment]
To reproduce the error, make sure you're in the virtual env already:
1) Check where the virtual env is located
```pipenv --venv```
2) Delete the virtual env from the project 
```pipenv --rm```
You'll probably still be inside _some_ virtual env (idk which or why), so just exit if you notice that
3) Make sure the virtual env is deleted from the path you got in Step 1.
4) Delete the repo from your computer
5) Re-clone the repo, make a virtual env and checkout to branch `develop`, install the packages, then try running the program ```python3 main.py```

I believe you should get the colorama (and emoji) error bc it's not specified in the Pipfile, unless you found some other way to get the package. You need to delete the virtual env bc it saves all the packages even if you delete the project from your computer. 

Lmk if you were able to reproduce the error.

**Comment by imthaghost** [comment]
> To reproduce the error, make sure you're in the virtual env already:
> 
> 1. Check where the virtual env is located
>    `pipenv --venv`
> 2. Delete the virtual env from the project
>    `pipenv --rm`
>    You'll probably still be inside _some_ virtual env (idk which or why), so just exit if you notice that
> 3. Make sure the virtual env is deleted from the path you got in Step 1.
> 4. Delete the repo from your computer
> 5. Re-clone the repo, make a virtual env and checkout to branch `develop`, install the packages, then try running the program `python3 main.py`
> 
> I believe you should get the colorama (and emoji) error bc it's not specified in the Pipfile, unless you found some other way to get the package. You need to delete the virtual env bc it saves all the packages even if you delete the project from your computer.
> 
> Lmk if you were able to reproduce the error.

Lmao I just noticed I never installed the module.... :) my bad

**Comment by imthaghost** [comment]
`Colorama` was installed globally on my computer, I installed the package into the virtual environment. I thought `colorama` was always an installed package for checkin, but I just realized I wrote code for python's built in terminal color functionality instead of using an external module. My bad guysssss <3

**Comment by tempor1s** [comment]
Looks good. Don’t merge yet as I need to add Colorama as a homebrew dependency. Thanks!

**Comment by TasfiaAddrita** [comment]
Don't forget to add emoji as well, that's also not installed.

**Comment by TasfiaAddrita** [comment]
> Looks good. Don’t merge yet as I need to add Colorama as a homebrew dependency. Thanks!

And `emoji`!

**Comment by tempor1s** [comment]
All set. Ready to merge :)

**Pull request merged**
