### PR TITLE
feature/meet

### PR DESCRIPTION
**Pull request by TasfiaAddrita**

### CODE REVIEW

**Review by tempor1s — CHANGES_REQUESTED** [review]
Looks good. I just need to update the import for it to work and I will merge.

**Comment by tempor1s** [comment]
Also. Shouldn't we be merging this into develop? Not master.

**Comment by TasfiaAddrita** [comment]
I figured master in case you guys were gonna reference meet.py in any other files

**Comment by tempor1s** [comment]
I think Gary and I are going to be building everything off of develop branch from now on, and only releases will be pushed to master every so often. Because ideally I want to setup Homebrew to use a binary instead of building from source every time and that will make that much easier.

**Pull request closed without merging**
